travis:
  secure:
    BINSTAR_TOKEN: pcWtLhK6wneW+UaohPe58Qli77b22UurC25Ik5a4ERy6r2PKoMxag43+Cr+iEAsEeBe4fZ27S1kuBxb8dm6vOBU8KiIwWeXaN4HDJwnvbEigUKiXJolYuzG+F6SfCTtbC6bXZROrNzjPKswqObtQGR2IHccayxyRU8HdGx7fw+/SWIJ9e4Fg86SW9Jqf68P86upyRgFn84tP2ELDwiglECQ/3eWwl4TmbxegeVQIETFR9pUQF8mzmO5+OpRULn+YWM7K+pXwAkwGfdphZhfYHZ2XsyhTZJscxvbR9X5p8awZ2JKmWBH444frc08WVj4HYL7meQx5p/w+EBvspfYZU3PxyKsJer4bNsBy3PHzQ6M7kPYoUdVchjY5wI4A+Tfx+bgMXYYA60Cs6gthZtNJ91qNeDwcsCsD9aiizyisYD6xcnUjySsZ4fWTouU2hqRvsrxuEsTbtqDLTEGvZAj2A5ZnEt5+V2avD9nJoTExRdWNmrwR/Yb7bqcDqEbt/SqEKgjZg2+fpe7MLOd/i2ReT8zA3N5ao1hN/OAcwXSluhk8s0m5Mhr2+Smp56IDoVQnE9IYZZbGWYTplYMv6dddrfXh0EiPCuWKFwvj9hxFS9m6urK9gP7vzyap/6XsXRtJ5dEzIoDvIEo2d13rong48vy+cj2YKzVusu2i2n6qrUQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
